---
title: "Lecture Commands - Data Wrangling with tidyverse"
author: "Lindsay N. Hayes"
date: 2026-07-13
draft: true
editor_options: 
  chunk_output_type: console
eval: false
---

```{r}
library(tidyverse)
```


import

```{r}
data <- read.csv(file = "taylorswift.csv",
                      header = TRUE, 
                      sep = ",", 
                      stringsAsFactors = TRUE)

class(data)
head(data)

data <- read_csv(file = "taylorswift.csv",
                      col_names = TRUE)
class(data)
head(data)

```

export

```{r}
# base R
write.csv(data, file = "data/taylorswift.csv")

# Tidyverse
write_csv(data, file = "data/taylorswift.csv")
```


## Unnest
```{r}

glimpse(starwars)

# lets look at the first row of starwars
starwars[1,]
starwars[1,11:14]

starwars$starships[1]

starwars |>
  select(name, films) |>
  unnest_longer(films)

library(taylor)
taylor_album_songs |> select(track_name, lyrics) |> 
  unnest_longer(lyrics)

```

## count
```{r}
taylor_album_songs |> count(album_name, sort = TRUE)

taylor_album_songs |> ggplot(aes(x = album_release, y = track_number, colour = album_name)) +
  geom_point()

taylor_album_songs |> 
  ggplot(aes(x = factor(album_release), y = track_number, colour = album_name)) +
  geom_point(size = 2) +
  ylab("number of tracks") + xlab("release date") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  scale_color_albums() + theme(legend.position = "none")
```


## group_by & summarize
```{r}
table(starwars$sex)


starwars |>
  group_by(sex) 


starwars |> count(sex)

starwars |>
  group_by(sex) |>
  summarize(mean_height = mean(height),
            sd_height = sd(height))

starwars |>
  drop_na(height, sex) |>
  group_by(sex) |>
  summarize(mean_height = mean(height),
            sd_height = sd(height))

```

## mutate
```{r}

datasets::Orange |> glimpse()
head(Orange)

## Calculate a rate of growth
Orange |> mutate(mm.per.day = circumference/age)

Orange |> mutate(mm.per.day = circumference/age) |>
  ggplot(aes(x = Tree, y = mm.per.day)) + 
  geom_boxplot() + 
  geom_point()


Orange |> ggplot(aes(x = age, y = circumference, color = Tree, group = Tree))  +
  geom_line(size = 2) + 
  theme_cowplot() + 
  scale_color_brewer(palette = "Set1")

```


