---
title: "Building a Quarto Website and Using GitHub"
description: "Reading for Class 07"
author: 
  - name: Lindsay Hayes
    url: https://lindsaynhayes.github.io
    affiliation: Department of Cell Biology, OUHSC
date: 2025-07-18
draft: false
---

::: callout-note
### Learning objectives

**At the end of this lesson you will be able to:**

- Create a GitHub repository 
- Setup a Quarto Website
- Publish your Quarto website through Github Pages
- Customize your Quarto Website
:::

### Pre-class Tasks

GitHub is a web-based platform that allows you to save files online, track changes to files, and share project files easily for improved collaboration. It has gained popularity in the scientific community as an effective tool for documenting research scripts, tracking edits or errors during analysis, and sharing project workflows with others. 

Please create accounts with GitHub and GitHub Desktop before our next class time:

- [Set up a Github Account Online](https://docs.github.com/en/get-started/start-your-journey/creating-an-account-on-github){target="_blank"} - Follow the steps from the **Signing up for a new personal account** section.

- [Set up Github Desktop Account on your computer](https://docs.github.com/en/desktop/installing-and-authenticating-to-github-desktop/installing-github-desktop){target="_blank"} - If you run into any problems with the installer for your operating system, email us as soon as possible. 

**Please write down your login information for Friday's class!**
